const $=s=>document.querySelector(s);
const video=$('#hero-video'), motion=$('#motion-toggle');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let motionWanted=false;
function updateMotion(){motion.setAttribute('aria-pressed',String(motionWanted));motion.textContent=motionWanted?'Pause background Ⅱ':'Play background ▷';video.classList.toggle('playing',motionWanted);}
async function playBackground(){try{await video.play();motionWanted=true;}catch{motionWanted=false;}updateMotion();}
motion.addEventListener('click',()=>{if(motionWanted){video.pause();motionWanted=false;updateMotion();}else playBackground();});
if(!reduced.matches && !navigator.connection?.saveData) playBackground();
const sections=[...document.querySelectorAll('main>section')];
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.rail a').forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}})},{threshold:.45});sections.forEach(s=>observer.observe(s));
window.addEventListener('scroll',()=>$('.header').classList.toggle('scrolled',scrollY>50),{passive:true});
const menu=$('.menu-toggle'),nav=$('#mobile-nav');function closeMenu(){nav.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.textContent='☰';}
menu.addEventListener('click',()=>{const open=nav.hidden;nav.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.textContent=open?'✕':'☰';});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const worlds={world:['assets/world.jpg','A vast city beneath a glowing blue sky'],forest:['assets/forest.jpg','Exploration amid the forests of Orbis'],ruins:['assets/ruins.jpg','Ancient ruins and hidden paths in Orbis']};
document.querySelectorAll('[data-world]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-world]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});const [src,alt]=worlds[b.dataset.world];$('#world-image').src=src;$('#world-image').alt=alt;}));
const characters=[{name:'Lute',image:'lute'},{name:'Theresia',image:'theresia'},{name:'Kalien',image:'kalien'}];
document.querySelectorAll('[data-character]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.character),c=characters[i];document.querySelectorAll('[data-character]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#character-image').src=`assets/${c.image}.jpg`;$('#character-image').alt=`Official ${c.name} gameplay preview`;$('#character-name').textContent=c.name;$('#character-number').textContent=`0${i+1} / 03`;$('#character-link').setAttribute('aria-label',`View ${c.name}'s official gameplay on Steam`);}));
const dialog=$('#trailer-dialog'),trailer=$('#trailer-video');document.querySelectorAll('[data-trailer]').forEach(b=>b.addEventListener('click',()=>{dialog.showModal();video.pause();trailer.play().catch(()=>{});}));$('#close-trailer').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{trailer.pause();if(motionWanted)video.play().catch(()=>{});});document.addEventListener('visibilitychange',()=>{if(document.hidden){video.pause();trailer.pause();}else if(motionWanted&&!dialog.open)video.play().catch(()=>{});});
